"""Add track_order

Revision ID: 30e948342792
Revises: 95f1a12a7da3
Create Date: 2024-10-23 13:56:43.511626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e948342792'
down_revision = '95f1a12a7da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_column('track_order')

    # ### end Alembic commands ###
