"""extend download status

Revision ID: 41cfd15a9050
Revises: a1478d4d2c47
Create Date: 2024-10-26 11:35:42.853550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cfd15a9050'
down_revision = 'a1478d4d2c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.alter_column('download_status',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.alter_column('download_status',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
