"""Added spotify_u12ri

Revision ID: 52d71c294c8f
Revises: 8843534fa7ea
Create Date: 2024-10-10 13:38:07.247311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d71c294c8f'
down_revision = '8843534fa7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downloaded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('filesystem_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('filesystem_path')
        batch_op.drop_column('downloaded')

    # ### end Alembic commands ###
