"""Add last_updated and last_changed fields to Playlist model

Revision ID: 8fcd403f0c45
Revises: 41cfd15a9050
Create Date: 2024-11-21 16:09:39.875467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcd403f0c45'
down_revision = '41cfd15a9050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_changed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_column('last_changed')
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
