"""Add lidarr_processed flag

Revision ID: d13088ebddc5
Revises: 18d056f49f59
Create Date: 2024-12-03 22:44:21.287754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13088ebddc5'
down_revision = '18d056f49f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lidarr_processed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('lidarr_processed')

    # ### end Alembic commands ###
